name: Build, Test & Lint

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: 0 4 * * 1

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [stable, beta, dev, "3.5.0"]
    steps:
      - uses: actions/checkout@v5
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart pub get

      - run: dart test

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get

      - run: dart pub global activate coverage ^1.0.0
      - run: dart pub global run coverage:test_with_coverage

      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # The linter throws an exception in 3.5.0:
        # https://github.com/dart-lang/sdk/issues/59560
        sdk: [stable, beta, dev, "3.6.0"]
    steps:
      - uses: actions/checkout@v5
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart pub get

      - run: dart analyze
